version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/static:/usr/share/nginx/static:ro
    networks:
      - admin_dashboard
    restart: on-failure
  
  postgres:
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: userdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - admin_dashboard
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_URL: postgres://user:pass@postgres:5432/userdb
      PORT: 3000
    depends_on:
      - postgres
    networks:
      - admin_dashboard
    ports:
      - "3000:3000"
      
networks:
  admin_dashboard:

volumes:
  postgres_data: